language: android
jdk: oraclejdk8
sudo: false
  
android:
  components:
     - tools
     - platform-tools
     - build-tools-27.0.3
     - android-27
     - extra-android-support
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  chmod +x gradlew
  
script:
- chmod +x ./gradlew 
- if [[ $LINT == 'true' ]]; then ./gradlew lint ; fi
- ./gradlew assembleDebug

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file: app/build/outputs/apk/debug/app-debug.apk
  on:
    tags: false
    all_branches: true
